[package]
name = "png-parse-problem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
png017 = { package = "png", version = "0.17" }
png016 = { package = "png", version = "0.16" }
